# -*- coding: utf-8 -*-
"""Object_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XUAk8RwDLMVxgreBlraNfa22ZLDWWNkF
"""

!pip3 install https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl

!wget https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/yolo.h5

!ls

from imageai.Detection import ObjectDetection

d = ObjectDetection()

d.setModelTypeAsYOLOv3()
d.setModelPath('yolo.h5')
d.loadModel()

import urllib
import numpy as np
import cv2
import matplotlib.pyplot as plt
# %matplotlib inline

def getimage(url):
  downloaded = urllib.request.urlopen(url)
  image = np.asarray(bytearray(downloaded.read()), dtype = 'uint8')
  image = cv2.imdecode(image, -1)
  image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
  
  return image

input_image = getimage('https://m.media-amazon.com/images/M/MV5BMzMwYWZkZjctZTU5Ny00MDNiLTlkMmYtNzkyODMwMGUxYzA2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_CR0,45,480,270_AL_UX477_CR0,0,477,268_AL_.jpg')
plt.imshow(input_image)
plt.axis('off')
plt.show()

output_image, objects = d.detectObjectsFromImage(input_type = 'array',
                                         output_type = 'array',
                                         input_image = input_image)

plt.figure(figsize = (10,10))
plt.imshow(output_image)
plt.axis('off')
plt.show()